// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpW3F3_u4aU56q9Shf_WPszs_-yv5KviU',
    appId: '1:1030403199802:web:a4d43941c393dff6933603',
    messagingSenderId: '1030403199802',
    projectId: 'daligas-bfd9b',
    authDomain: 'daligas-bfd9b.firebaseapp.com',
    storageBucket: 'daligas-bfd9b.firebasestorage.app',
    measurementId: 'G-KNW5GHXQCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByTVMTJRgY9I3hmqz5ktr8nqKTAdMQGU',
    appId: '1:1030403199802:android:e6b305ca7db99e99933603',
    messagingSenderId: '1030403199802',
    projectId: 'daligas-bfd9b',
    storageBucket: 'daligas-bfd9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHd7urinTuhjL8tGSJZAgRy-IMai5a5Ps',
    appId: '1:1030403199802:ios:da2c9758548218ad933603',
    messagingSenderId: '1030403199802',
    projectId: 'daligas-bfd9b',
    storageBucket: 'daligas-bfd9b.firebasestorage.app',
    iosBundleId: 'com.example.daligas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHd7urinTuhjL8tGSJZAgRy-IMai5a5Ps',
    appId: '1:1030403199802:ios:da2c9758548218ad933603',
    messagingSenderId: '1030403199802',
    projectId: 'daligas-bfd9b',
    storageBucket: 'daligas-bfd9b.firebasestorage.app',
    iosBundleId: 'com.example.daligas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpW3F3_u4aU56q9Shf_WPszs_-yv5KviU',
    appId: '1:1030403199802:web:4680d728e5dedde8933603',
    messagingSenderId: '1030403199802',
    projectId: 'daligas-bfd9b',
    authDomain: 'daligas-bfd9b.firebaseapp.com',
    storageBucket: 'daligas-bfd9b.firebasestorage.app',
    measurementId: 'G-Z4KCM65RPS',
  );
}
